version: '3.7'
services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27020:27017
    volumes:
      - mongodb_data_container:/data/db
  numbat-express:
    build: ./huisnieuws/server
    restart: always
    ports:
      - 8000:8000

volumes:
  mongodb_data_container:
